version: '3'

services:

  app:
    build:
      context: .
    container_name: vue-login-app
    user: "node"
    environment:
      - PORT:8080
      - SERVER_PORT:3000
    working_dir: /var/www
    restart: always
    volumes:
      - ./:/var/www
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
      - "3000:3000"
    networks:
      - vue-login

networks:
  vue-login:
    driver: bridge

